### ISSUE TITLE
Player Kicking Bug - Unpayable

### ISSUE THREAD

**Issue by ProtoGhost** [andrei1058/BedWars1058#149] opened 2021-11-30 14:01 UTC
****Describe the bug****
**when you join BedWar and leave the match and you will join again you will get kick**

To Reproduce

Go to config.yml
Set enable-lobby-sidebar: to false
Restart the server
Join on a random arena
Leave the arena
Join again on a random arena
[bedwar1058 errors on bungeecord.txt](https://github.com/andrei1058/BedWars1058/files/7626182/bedwar1058.errors.on.bungeecord.txt)
![kick msg](https://user-images.githubusercontent.com/67905221/144060294-d7682f24-20a5-42f8-8b79-a8cc0ab4755f.png)

[14:47:33 INFO]: UUID of player 0_ProtoGhost is uuid
[14:47:33 INFO]: 0_ProtoGhost logged in with entity id 59 at ([world]0.45276530719922276, 80.0, 0.5266597877318901)
[14:47:42 INFO]: 0_ProtoGhost issued server command: /bw join Solo
[14:47:51 INFO]: 0_ProtoGhost issued server command: /bw join Solo
[14:47:51 INFO]: 0_ProtoGhost lost connection: Disconnected

**no errors showing on bedwar game server console  only error appearing on bungeed server console**

BedWar1058 - 21.11.2

**Comment by ajgeiss0702** [comment] 2021-11-30 15:31
Duplicate of #129

**Closed as completed by ajgeiss0702** 2021-11-30 15:31 UTC
Labels: bug

**Comment by ProtoGhost** [comment] 2021-12-16 07:31
when it will be fixed?
