### ISSUE TITLE
Broken generators after all beds are broken

### ISSUE THREAD

**Issue by joohnaquino** [andrei1058/BedWars1058#678] opened 2023-02-17 23:15 UTC
**Describe the bug**
After the event "beds destroy" all diamond and emerald generators are "broken", all blocks below the generator disappear

**To Reproduce**
I don't know how to reset this since it's the default setting

**Expected behavior**
It was simply and obviously not supposed to happen.

**Screenshots**
![2023-02-16_23 26 00](https://user-images.githubusercontent.com/120399502/219814556-62b090fd-46aa-41f1-9c37-612c9d49e464.png)
![2023-02-16_23 26 03](https://user-images.githubusercontent.com/120399502/219814925-7e713a8f-7614-41b2-8c32-333e20c18a95.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Server software PaperSpigot-445
 - Server Version 1.8.8
 - Plugin Version 23.2

**Comment by tomkeuper** [comment] 2023-02-18 00:35
Duplicate of #529

**Closed as not planned by tomkeuper** 2023-02-18 00:35 UTC
Labels: bug
