### ISSUE TITLE
Make The TeamColor Placeholder return Vault-Prefix Color When in waiting.

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#390] opened 2022-02-15 07:29 UTC
**Is your feature request related to a problem? Please describe.**
Its a suggestion more-than a feature request

**Screenshot**
![image](https://user-images.githubusercontent.com/93807992/154013600-3d690485-9820-4c09-91f0-d9f21c250494.png)

**Describe the solution you'd like**
Make it so that the placeholder which returns the color of the team which the player is in, Return The %vault_prefix_color%  instead of just showing plane white color in the waiting-Spawn before game start(Not in Main-Lobby)

**Describe alternatives you've considered**
Could use TAB but it is not perfectly working.

**Additional context**
Hope Any One Of The Contributors Pays Attention To My Suggestion/Feature Request.

**Comment by DeusDrizzyy** [comment] 2022-02-24 11:13
Same #384

**Comment by ajgeiss0702** [comment] 2022-02-25 16:30
Duplicate of #384

**Closed as completed by ajgeiss0702** 2022-02-25 16:30 UTC
Labels: enhancement
