### ISSUE TITLE
Team Player Balancer

### ISSUE THREAD

**Issue by EvilG-MC** [andrei1058/BedWars1058#583] opened 2022-08-15 13:24 UTC
**Is your feature request related to a problem?**
In itself it is not such a critical problem, but I think it can be annoying, but When there are 4 players or more in an arena there is a probability depending on the type of arena, that they will move to odd teams, what I mean, if the arena is 4v4v4v4v4, 4 of them will go to a single team, instead of splitting them in 2, *(or in one, and each one to an island, it would have to be seen)*

**Describe the solution you'd like**
A solution could be that when there are odd numbers to the maximum capacity of the arena and the type, the players are divided and placed in the necessary islands, eg: 3 players in an arena of duos, one player goes to each island

**Comment by tomkeuper** [comment] 2023-02-16 20:13
Duplicate of #179

**Closed as not planned by tomkeuper** 2023-02-16 20:13 UTC
Labels: enhancement
