### ISSUE TITLE
Rejoin not able to place blocks

### ISSUE THREAD

**Issue by Askarionn** [andrei1058/BedWars1058#145] opened 2021-11-30 07:44 UTC
**Describe the bug**
When you rejoin on a arena you can't place blocks

**To Reproduce**
1. Join a arena
2. Leave the server
3. Rejoin the bedwars server

**Expected behavior**
You should be able to place blocks

**Screenshots**
https://imgur.com/a/5KM7kgY

**System (please complete the following information):**
 - OS: Debian 10
 - Server software PaperSpigot
 - Server Version 1.8.8
 - Plugin Version 21.11.1

**Additional context**
-

**Comment by ajgeiss0702** [comment] 2021-11-30 07:46
Duplicate of #55

**Closed as completed** 2021-12-12 21:51 UTC
Labels: bug, duplicate
