### ISSUE TITLE
Sword Removed From Existance

### ISSUE THREAD

**Issue by sreyas0001** [andrei1058/BedWars1058#433] opened 2022-03-08 14:29 UTC
__________To Reproduce________________
1. Enter A Game
2. Buy any two different swords
3. Throw one sword down
4. Then Try Taking it back
5. You see the sword you picked will disappear(Even if its a higher tier or lower)
_____________Request(Recommend/Fix)_____________________
Please Fix It, If its a hypixel feature then there should be option for toggling.

**Comment by tomkeuper** [comment] 2023-03-08 13:08
I will mark this one as a dupe because the more recent one is already implemented and will be merged in the next release.

**Comment by tomkeuper** [comment] 2023-03-08 13:08
Duplicate of #686

**Closed as not planned by tomkeuper** 2023-03-08 13:08 UTC
Labels: bug
