### ISSUE TITLE
Player-head for Stats GUI not changing to the player's skin's head

### ISSUE THREAD

**Issue by cjtganzon** [andrei1058/BedWars1058#659] opened 2023-02-06 07:56 UTC
**Describe the bug**

Using the original config, the Stats item in the lobby and waiting room do not change to the players skins head.
**To Reproduce**
1. Install bedwars1058 23.2 with the default config.
2. Go to the server and look at Stats item in the hotbar.
3. Look at the Steve in the face and tell him hello.

**Expected behavior**

To change the player-head item to the player's skin's head.
**Screenshots**

![image](https://user-images.githubusercontent.com/62964779/216914975-8baf0ab9-c276-4c1b-9a01-d07ab71bf3df.png)

**System (please complete the following information):**
 - OS: Windows 11
 - Server software: Purpur
 - Server Version: 1.19.3 
 - Plugin Version: 23.2 

**Additional context**

**Comment by tomkeuper** [comment] 2023-02-19 15:44
just found out.
Duplicate of #333

**Closed as not planned by tomkeuper** 2023-02-19 15:44 UTC
Labels: bug
