### ISSUE TITLE
The Blast Proof Glass Incident 2023

### ISSUE THREAD

**Issue by porudev** [andrei1058/BedWars1058#706] opened 2023-03-08 07:30 UTC
**Describe the bug**
The blast proof glass, it doesn't blast proof. I mean yes it protect it self but not others inside of it

**To Reproduce**
You cover up anything with full blast proof glass, blast it with a 1 or a bunch of tnt and the glass should be fine but anything inside it

**Expected behavior**
Stuff inside Blass proof glass should be protected

**Screenshots**
This should be unnecessary

**System:**
 - OS: GNU/Linux
 - Server software: PaperMC
 - Server Version: 1.8.8
 - Plugin Version: bedwars-plugin-23.2.2-BETA2
 
**Additional context**
No additional context needed

**Comment by tomkeuper** [comment] 2023-03-08 13:03
Duplicate of #292

**Closed as not planned by tomkeuper** 2023-03-08 13:03 UTC
Labels: bug
