### ISSUE TITLE
Blast proof glass does not work as intended <1.13

### ISSUE THREAD

**Issue by IIHERO4** [andrei1058/BedWars1058#458] opened 2022-03-25 13:25 UTC
**Describe the bug**
Glass-Blast Proof does not protect blocks behind itself https://github.com/andrei1058/BedWars1058/blob/ca839aa9ad466a241f47e43d7977523fbea08e0a/bedwars-plugin/src/main/java/com/andrei1058/bedwars/listeners/BreakPlace.java#L511
I faced this issue as the original bedwars (hypixel) clearly protected blocks behind the glass.

**To Reproduce**
1. place blast proof glass in such order 
![2022-03-25_15 17 30](https://user-images.githubusercontent.com/46909116/160127964-1b0fbdb0-3ee1-44d8-a03b-e983654723bb.png)

2. simply place the tnt where the redstone block is

![2022-03-25_15 17 36](https://user-images.githubusercontent.com/46909116/160128003-5c7d108f-ae92-48a5-b4a5-628fc591e0f5.png)

**Expected behavior**
![2022-03-25_15 17 30](https://user-images.githubusercontent.com/46909116/160127964-1b0fbdb0-3ee1-44d8-a03b-e983654723bb.png)

**Screenshots**
The undesired behavior:
![2022-03-25_15 22 51](https://user-images.githubusercontent.com/46909116/160128708-f9d61e57-fdf0-4d9e-877c-daaa1b992c39.png)

**System (please complete the following information):**
 - OS: Linux
 - Server software ImanitySpigot
 - Server Version 1.8.8
 - Plugin Version **Lost track of the original version sorry**

**Additional context**
So on our server, we implemented a fix to produce the same behavior as the original bedwars implementation but we did that on an old version of bedwars1058, so im hesitant to make a pull request as the issue may have been fixed in the current version. (I need confirmation on weather to do it or not)
I will be more than happy to port over the code from our server :)

**Comment by IIHERO4** [comment] 2022-03-25 14:21
Worth Noting that there are some cases where our implementation doesnt work, so this needs a proper look from another dev bc i can't think of anyway other than rewriting the whole `e.blockList()` which will require some work on calculating the explosion outcome(a new  `e.blockList()`)

**Comment by ajgeiss0702** [comment] 2022-03-26 01:24
duplicate of #292

If you do fix it, feel free to make a PR too. Even if it doesn't fully work, its probably better than just almost completely not working

**Closed as completed by ajgeiss0702** 2022-03-26 01:24 UTC
Labels: bug
