### ISSUE TITLE
Unbreakable swords

### ISSUE THREAD

**Issue by Sgattix** [andrei1058/BedWars1058#542] opened 2022-06-16 14:33 UTC
Hi, i don't know if this is a bug or a misconfiguration problem, but how do I put unbreakable swords, without editing the code?

**Comment by Memexurer** [comment] 2022-07-07 12:54
#370

**Comment by tomkeuper** [comment] 2023-02-16 19:10
Duplicate of #370

**Comment by tomkeuper** [comment] 2023-02-16 19:10
Duplicate of #245

**Closed as completed by tomkeuper** 2023-02-16 19:10 UTC
Labels: bug
