### ISSUE TITLE
Placeholder Not Working

### ISSUE THREAD

**Issue by actuallySoheil** [andrei1058/BedWars1058#680] opened 2023-02-19 20:32 UTC
**Describe the bug**
``{wins}`` Placeholder in the sidebar doesn't work.

**To Reproduce**
1. Go to server
2. See that placeholder is not working

**Expected behavior**
The placeholder should return the actual player wins instead of ``{wins}``

**Screenshots**
![image](https://user-images.githubusercontent.com/124730657/219973631-5bfe8f01-0a15-40b6-b10f-739f3cdd108d.png)

**System**:
 - OS: Windows
 - Server software: NachoSpigot
 - Server Version: 1.8.8
 - Plugin Version: v23.2

**Additional context**
BedWars1058 is running on default configuration.

**Comment by tomkeuper** [comment] 2023-02-19 21:36
Duplicate of #674

Download the fix here: https://discord.com/channels/201345265821679617/1074361958876315698
latest pinned has some more fixes aswell

**Closed as completed by tomkeuper** 2023-02-19 21:36 UTC
Labels: bug
