### ISSUE TITLE
Sidebar error

### ISSUE THREAD

**Issue by itdoesnotmatterr** [andrei1058/BedWars1058#698] opened 2023-03-04 19:14 UTC
**Describe the bug**

If minPlayers is for example 2 and we join the game as a 2nd player, the sidebar lines are duplicated

**To Reproduce**
Set minPlayers in the arena file to for example 1 and join the game (this works for any number of players, whether alone or with someone)

**Expected behavior**
The sidebar should display normally instead of being duplicated

**Screenshots**
![image](https://user-images.githubusercontent.com/126983065/222924519-af92226b-412d-4fdb-8bbb-af872abde16a.png)

**System (please complete the following information):**
 - OS: Windows
 - Server software Spigot
 - Server Version 1.12.2
 - Plugin Version 23.2.1

**Additional context**
None

**Comment by tomkeuper** [comment] 2023-03-05 13:19
duplicate of #690

**Closed as not planned by tomkeuper** 2023-03-05 13:19 UTC
Labels: bug
