### ISSUE TITLE
[Bug] When purchasing a sword or bow in the shop, the item is not tagged as unbreakable

### ISSUE THREAD

**Issue by ImYenil** [andrei1058/BedWars1058#675] opened 2023-02-16 16:11 UTC
**Describe the bug**
When purchasing a sword or bow in the shop, the item is not tagged as unbreakable

**To Reproduce**
X

**Expected behavior**
X

**Screenshots**
X

**System (please complete the following information):**
 - OS:  Windows
 - Server software  spigot
 - Server Version  1.8.8
 - Plugin Version   23.2

**Additional context**
 X

**Comment by tomkeuper** [comment] 2023-02-16 19:11
Duplicate of #245

**Closed as completed by tomkeuper** 2023-02-16 19:11 UTC
Labels: bug
