### ISSUE TITLE
Sword with durability

### ISSUE THREAD

**Issue by ezVelar** [andrei1058/BedWars1058#603] opened 2022-09-22 22:31 UTC
Hi, the sword in the shop in Iron, gold and diamond are with durability
i try to set "permanent" the item in shop.yml but whe i death the sword remain in my inventory and the most of player doesn't want this
please can fix this? thank you very much!

Server version: Spigot 1.8.8
Client version: 1.8.9
OS: Ubuntu 20.04
Plugin version: 22.7

**Comment by porudev** [comment] 2023-01-09 19:49
+1

**Comment by tomkeuper** [comment] 2023-02-21 11:53
Duplicate of #245 
Will be fixed in new release

**Closed as not planned by tomkeuper** 2023-02-21 11:53 UTC
Labels: bug
