### ISSUE TITLE
tnt can break blocks behind the glass

### ISSUE THREAD

**Issue by BLACKGAMER1221** [andrei1058/BedWars1058#738] opened 2023-03-25 18:11 UTC
**Describe the bug**
tnt can break blocks behind the glass and you can break grass

**To Reproduce**
1.place blocks around the bed
2. place glasses around the blocks
3. place tnt around the glass
4. blocks behind the glass breaked

**Screenshots**
[](https://cdn.discordapp.com/attachments/1074361958876315698/1089247372850245652/javaw_2023-03-25_22-27-19-134.mp4)

**System (please complete the following information):**
 - OS: linux obuntu
 - Server software paper
 - Server Version 1.12.2
 - Plugin Version 23.2.2 BETA4

**Comment by MajliTech** [comment] 2023-03-26 11:33
Duplicate of #292 and should be closed.

**Comment by tomkeuper** [comment] 2023-03-26 11:37
Duplicate of #292

**Closed as not planned** 2023-03-26 11:37 UTC
Labels: bug
