### ISSUE TITLE
Plugin Bedwars

### ISSUE THREAD

**Issue by Adamek038271** [andrei1058/BedWars1058#383] opened 2022-02-11 17:44 UTC
**Describe the bug**
Plugin don't work and the game is not loading

**Expected behavior**
Plugin does work

**Screenshots**
![image](https://user-images.githubusercontent.com/94638387/153641646-64bcf250-556f-48a7-800b-3efb30fd45d2.png)
![image](https://user-images.githubusercontent.com/94638387/153641717-5dcfff3e-fdf1-4794-9e3c-1c7561eba677.png)
![image](https://user-images.githubusercontent.com/94638387/153641874-c36698bf-3393-4996-914a-85567e829744.png)

**System (please complete the following information):**
 - OS: Windows
 - Server software [spigot]
 - Server Version [1.8.8]
 - Plugin Version [22.2]

**Comment by ajgeiss0702** [comment] 2022-02-11 18:00
Duplicate of #337

**Closed as completed by ajgeiss0702** 2022-02-11 18:00 UTC
Labels: bug
