### ISSUE TITLE
Invisibility Foot prints

### ISSUE THREAD

**Issue by AstroLands** [andrei1058/BedWars1058#164] opened 2021-12-03 08:46 UTC
**Is your feature request related to a problem? Please describe.**
When walking with invis pot footprints aint visible

**Describe the solution you'd like**
When u drink invisibility pot there still will be footprints visible

**Describe alternatives you've considered**
there's not alternatives

**Additional context**
Nope

**Comment by CoachYT1** [comment] 2021-12-03 10:42
Duplicate of #30

**Closed** 2021-12-03 21:12 UTC
Labels: duplicate, enhancement
